### ISSUE TITLE
StitchData integration failures

### ISSUE THREAD

**Issue by Kobold** [singer-io/tap-ringcentral#13]
Is anybody successfully using this tap? It doesn't seem to work for me. I've included an error log below.

I did by best to validate that credentials were set up correctly and the RingCentral app was configured correctly according to this setup guide: https://www.stitchdata.com/docs/integrations/saas/ringcentral#setup

Notably, it looks like someone on the dbt-labs version of this tap was running into this exact same error in March 2020: This is a followup on this issue: https://github.com/dbt-labs/tap-ringcentral/issues/8 As there's been no change in 1.5 years, I'm not sure if I'm doing something wrong or this integration is broken and unmaintained.

```
2021-10-13 17:27:04,373Z   main - INFO Running tap-ringcentral version 1.0.1 and target-stitch version 3.2.0
2021-10-13 17:27:05,572Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobStarted ), use_ssl( true )
2021-10-13 17:27:05,577Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobFinished ), use_ssl( true )
2021-10-13 17:27:05,578Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.streamRecordCount ), use_ssl( true )
2021-10-13 17:27:06,588Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobStarted [41] at offset None
2021-10-13 17:27:06,590Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-ringcentral --config /tmp/tap_discover_config.json --discover
2021-10-13 17:27:07,485Z    tap - INFO Starting discovery.
2021-10-13 17:27:07,521Z   main - INFO Tap exited normally.
2021-10-13 17:27:07,521Z   main - INFO Saving list of discovered streams
2021-10-13 17:27:07,576Z   main - INFO Saving structure of stream contacts (tap_stream_id: contacts)
2021-10-13 17:27:07,631Z   main - INFO Saving structure of stream call_log (tap_stream_id: call_log)
2021-10-13 17:27:07,685Z   main - INFO Saving structure of stream company_call_log (tap_stream_id: company_call_log)
2021-10-13 17:27:07,720Z   main - INFO Saving structure of stream messages (tap_stream_id: messages)
2021-10-13 17:27:07,759Z   main - INFO Starting tap: tap-env/bin/tap-ringcentral --config /tmp/tap_config.json
2021-10-13 17:27:08,418Z    tap - INFO Starting sync.
2021-10-13 17:27:08,419Z    tap - CRITICAL 'NoneType' object has no attribute 'streams'
2021-10-13 17:27:08,419Z    tap - Traceback (most recent call last):
2021-10-13 17:27:08,419Z    tap -   File "tap-env/bin/tap-ringcentral", line 33, in <module>
2021-10-13 17:27:08,419Z    tap -     sys.exit(load_entry_point('tap-ringcentral==1.0.1', 'console_scripts', 'tap-ringcentral')())
2021-10-13 17:27:08,419Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 192, in wrapped
2021-10-13 17:27:08,419Z    tap -     return fnc(*args, **kwargs)
2021-10-13 17:27:08,419Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_ringcentral/__init__.py", line 66, in main
2021-10-13 17:27:08,419Z    tap -     runner.do_sync()
2021-10-13 17:27:08,419Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_ringcentral/__init__.py", line 22, in do_sync
2021-10-13 17:27:08,419Z    tap -     streams = self.get_streams_to_replicate()
2021-10-13 17:27:08,419Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_framework/__init__.py", line 26, in get_streams_to_replicate
2021-10-13 17:27:08,419Z    tap -     for stream_catalog in self.catalog.streams:
2021-10-13 17:27:08,420Z    tap - AttributeError: 'NoneType' object has no attribute 'streams'
2021-10-13 17:27:08,451Z   main - INFO Connection check failed
2021-10-13 17:27:10,122Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [43] at offset None
2021-10-13 17:27:10,127Z   main - INFO No tunnel subprocess to tear down
2021-10-13 17:27:10,127Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "'NoneType' object has no attribute 'streams'".
```

**Comment by wwalker022** [comment]
Is there any status on getting this resolved? I'm getting the same error in Stitch.

**Comment by lavarthan** [comment]
@wwalker022  have you found any solution? I'm experiencing the same issue

**Comment by yjhuoh** [comment]
pathlight's fork is probably your best bet 

https://github.com/Pathlight/tap-ringcentral

unclear if the person developing it ever finished but of the different forks of this repo that looks to have the most work done on it
