### ISSUE TITLE
RIngCentral to Power BI integration 

### ISSUE THREAD

**Issue by roshwewe** [singer-io/tap-ringcentral#14]
I'm getting the below error code when i tried to connect the ringcentral app on stitch settings - please help me out 

2022-01-10 08:49:39,852Z   main - INFO Running tap-ringcentral version 1.0.1 and target-stitch version 3.2.0
2022-01-10 08:49:40,717Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobStarted ), use_ssl( true )
2022-01-10 08:49:40,720Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobFinished ), use_ssl( true )
2022-01-10 08:49:40,721Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.streamRecordCount ), use_ssl( true )
2022-01-10 08:49:40,771Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobStarted [18] at offset None
2022-01-10 08:49:40,774Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-ringcentral --config /tmp/tap_discover_config.json --discover
2022-01-10 08:49:41,130Z    tap - CRITICAL 400 Client Error: Bad Request for url: https://platform.ringcentral.com/restapi/oauth/token
2022-01-10 08:49:41,130Z    tap - Traceback (most recent call last):
2022-01-10 08:49:41,131Z    tap -   File "tap-env/bin/tap-ringcentral", line 33, in <module>
2022-01-10 08:49:41,131Z    tap -     sys.exit(load_entry_point('tap-ringcentral==1.0.1', 'console_scripts', 'tap-ringcentral')())
2022-01-10 08:49:41,131Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 192, in wrapped
2022-01-10 08:49:41,131Z    tap -     return fnc(*args, **kwargs)
2022-01-10 08:49:41,131Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_ringcentral/__init__.py", line 58, in main
2022-01-10 08:49:41,131Z    tap -     client = RingCentralClient(args.config)
2022-01-10 08:49:41,131Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_ringcentral/client.py", line 24, in __init__
2022-01-10 08:49:41,131Z    tap -     self.refresh_token, self.access_token = self.get_authorization()
2022-01-10 08:49:41,131Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_ringcentral/client.py", line 48, in get_authorization
2022-01-10 08:49:41,131Z    tap -     response.raise_for_status()
2022-01-10 08:49:41,131Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
2022-01-10 08:49:41,131Z    tap -     raise HTTPError(http_error_msg, response=self)
2022-01-10 08:49:41,131Z    tap - requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://platform.ringcentral.com/restapi/oauth/token
2022-01-10 08:49:41,159Z   main - INFO Tap exited abnormally with status 1
2022-01-10 08:49:41,724Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [36] at offset None
2022-01-10 08:49:41,725Z   main - INFO No tunnel subprocess to tear down
2022-01-10 08:49:41,725Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "400 Client Error: Bad Request for url: https://platform.ringcentral.com/restapi/oauth/token".

**Comment by roshwewe** [comment]
any update ?
