### ISSUE TITLE
Stitch integration issues with RingCentral

### ISSUE THREAD

**Issue by uschles** [singer-io/tap-ringcentral#16]
Hi there,
I'm trying to create a RingCentral integration using Stitch but I can't seem to get this to work. I keep getting these errors. Has anyone seen this and found a way around this?

`2023-04-14 16:06:16,619Z   main - INFO Running tap-ringcentral version 1.0.1 and target-stitch version 3.2.1
2023-04-14 16:06:17,768Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-ringcentral --config /tmp/tap_discover_config.json --discover
2023-04-14 16:06:18,082Z    tap - CRITICAL 400 Client Error: Bad Request for url: https://platform.devtest.ringcentral.com/restapi/oauth/token
2023-04-14 16:06:18,082Z    tap - Traceback (most recent call last):
2023-04-14 16:06:18,082Z    tap -   File "/code/orchestrator/tap-env/bin/tap-ringcentral", line 33, in <module>
2023-04-14 16:06:18,082Z    tap -     sys.exit(load_entry_point('tap-ringcentral==1.0.1', 'console_scripts', 'tap-ringcentral')())
2023-04-14 16:06:18,082Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/singer/utils.py", line 192, in wrapped
2023-04-14 16:06:18,082Z    tap -     return fnc(*args, **kwargs)
2023-04-14 16:06:18,082Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_ringcentral/__init__.py", line 58, in main
2023-04-14 16:06:18,082Z    tap -     client = RingCentralClient(args.config)
2023-04-14 16:06:18,082Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_ringcentral/client.py", line 24, in __init__
2023-04-14 16:06:18,082Z    tap -     self.refresh_token, self.access_token = self.get_authorization()
2023-04-14 16:06:18,082Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_ringcentral/client.py", line 48, in get_authorization
2023-04-14 16:06:18,083Z    tap -     response.raise_for_status()
2023-04-14 16:06:18,083Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/requests/models.py", line 935, in raise_for_status
2023-04-14 16:06:18,083Z    tap -     raise HTTPError(http_error_msg, response=self)
2023-04-14 16:06:18,083Z    tap - requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://platform.devtest.ringcentral.com/restapi/oauth/token
2023-04-14 16:06:18,104Z   main - INFO Tap exited abnormally with status 1
2023-04-14 16:06:18,108Z   main - INFO No tunnel subprocess to tear down
2023-04-14 16:06:18,108Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "400 Client Error: Bad Request for url: https://platform.devtest.ringcentral.com/restapi/oauth/token".`

**Comment by jmerone** [comment]
Did anyone ever figure a workaround for this?

> Hi there, I'm trying to create a RingCentral integration using Stitch but I can't seem to get this to work. I keep getting these errors. Has anyone seen this and found a way around this?
> 
> `2023-04-14 16:06:16,619Z main - INFO Running tap-ringcentral version 1.0.1 and target-stitch version 3.2.1 2023-04-14 16:06:17,768Z main - INFO Starting tap to discover schemas: tap-env/bin/tap-ringcentral --config /tmp/tap_discover_config.json --discover 2023-04-14 16:06:18,082Z tap - CRITICAL 400 Client Error: Bad Request for url: https://platform.devtest.ringcentral.com/restapi/oauth/token 2023-04-14 16:06:18,082Z tap - Traceback (most recent call last): 2023-04-14 16:06:18,082Z tap - File "/code/orchestrator/tap-env/bin/tap-ringcentral", line 33, in <module> 2023-04-14 16:06:18,082Z tap - sys.exit(load_entry_point('tap-ringcentral==1.0.1', 'console_scripts', 'tap-ringcentral')()) 2023-04-14 16:06:18,082Z tap - File "/code/orchestrator/tap-env/lib/python3.9/site-packages/singer/utils.py", line 192, in wrapped 2023-04-14 16:06:18,082Z tap - return fnc(*args, **kwargs) 2023-04-14 16:06:18,082Z tap - File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_ringcentral/__init__.py", line 58, in main 2023-04-14 16:06:18,082Z tap - client = RingCentralClient(args.config) 2023-04-14 16:06:18,082Z tap - File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_ringcentral/client.py", line 24, in __init__ 2023-04-14 16:06:18,082Z tap - self.refresh_token, self.access_token = self.get_authorization() 2023-04-14 16:06:18,082Z tap - File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_ringcentral/client.py", line 48, in get_authorization 2023-04-14 16:06:18,083Z tap - response.raise_for_status() 2023-04-14 16:06:18,083Z tap - File "/code/orchestrator/tap-env/lib/python3.9/site-packages/requests/models.py", line 935, in raise_for_status 2023-04-14 16:06:18,083Z tap - raise HTTPError(http_error_msg, response=self) 2023-04-14 16:06:18,083Z tap - requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://platform.devtest.ringcentral.com/restapi/oauth/token 2023-04-14 16:06:18,104Z main - INFO Tap exited abnormally with status 1 2023-04-14 16:06:18,108Z main - INFO No tunnel subprocess to tear down 2023-04-14 16:06:18,108Z main - INFO Exit status is: Discovery failed with code 1 and error message: "400 Client Error: Bad Request for url: https://platform.devtest.ringcentral.com/restapi/oauth/token".`
